### ISSUE TITLE
maybe a bug

### ISSUE THREAD

**Issue by heyuanlong** [hunterhug/go-image#1]
func SaveImage(path string, img *image.RGBA, filetype string) (err error) {
	file, err := os.Create(path)
	if err != nil {
		return
	}
	if filetype == "png" {
		err = png.Encode(file, img)
	} else if filetype == "jpeg" {
		err = jpeg.Encode(file, img, nil)
	} else {
		err = ExtNotSupportError
	}
	return
}

add code :defer file.Close()

**Comment by hunterhug** [comment]
you are right! It cause nothing,but add it maybe better.
